#!/usr/bin/env python

import re
import os
import subprocess

def my_func(account, sender, message, conversation, flags):
    print sender
    print message
    name = re.search (ur'^(.*)@', sender)
    text = re.search (ur"<body>(.*)</body>", message)
    #print name.group(1), ":", text.group(1)
    popup = 'naughty.notify({ font="terminus 10",hover_timeout = 0.2, timeout = 0, text= "' + sender.encode('utf-8') + ' : ' + message.encode('utf-8') + '" })\n'
    #print popup
    proc = subprocess.Popen(['awesome-client', '-'],
                        stdin=subprocess.PIPE,)
    proc.communicate(popup)


import dbus, gobject
from dbus.mainloop.glib import DBusGMainLoop
dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
bus = dbus.SessionBus()

bus.add_signal_receiver(my_func,
												dbus_interface="im.pidgin.purple.PurpleInterface",
																								signal_name="ReceivedImMsg")

loop = gobject.MainLoop()
loop.run()
